### ISSUE TITLE
가만히 있을 때 점프가 안됨

### ISSUE THREAD

**Issue by issacclicker** [issacclicker/gamemaru#9]
플레이어가 정지 상태로 스페이스바 누르면 점프가 안되요.

**Comment by tangerlyn** [comment]
이거 내가 디버깅 용으로 넣어놨던 217번째 줄 Debug.Log($"isGrounded: {isGrounded}");  주석 풀어서 확인해보면, 가만히 있을 때는 모델이 지면에 안 붙어있어서 점프가 안됨. 

지면에 안 붙어있을 때도 점프가 가능하게 하면, 공중에서 점프 가능하게 됨(중복 점프 가능)
-> 지면에 안 붙어있어도 점프가 되지만 한번에 점프할 수 있는 횟수를 정해서 더블 점프 방지하도록 바꿈.

lobby_2 브랜치 playermovement 스크립트에 주석으로 표시해둔 '점프 바뀐 부분' 1, 2, 3 참고
